### PR TITLE
Add PIDs of known Nordic devices

### PR DESCRIPTION
**Pull request by pszkotak**
This adds PIDs of known Nordic devices:

- 0x521f USB Boootloader
- 0xcafe OpenThread samples
- 0x154a IEEE802.15.4 sniffer

Signed-off-by: Piotr Szkotak <piotr.szkotak@nordicsemi.no>

### CODE REVIEW

**Comment by bencefr** [comment]
Hi @pszkotak , do the newly listed devices provide DFU trigger interface as the first USB endpoint?
I believe this change has unintended consequences .

**Comment by pszkotak** [comment]
> Hi @pszkotak , do the newly listed devices provide DFU trigger interface as the first USB endpoint?
> I believe this change has unintended consequences .

In some cases they do.
OpenThread (0xCAFE) can be build with it, sniffer (0x154a) for sure did it in older revisions, I'm not 100% sure about the current one. Bootloader does not provide the trigger interface as the interface is used to enter it.

As far as I see there is a different way to check if the trigger interface is present:
https://github.com/NordicSemiconductor/nrf-device-lister-js/blob/365c44313d3141c0d20d2f245214743074801874/src/device-lister.js#L82-L89

I did some 
Please describe what consequences you have in mind.

**Comment by bencefr** [comment]
You are right, I mixed up the traits. Also, thanks for the PR!

**Review by bencefr — APPROVED** [review]

**Comment by pszkotak** [comment]
Okay, so now we need to figure out if we should merge this or revert previous changes - https://github.com/NordicSemiconductor/nrf-device-lister-js/issues/69

If there is no need to filter PIDs IMO we should just stay with checking the VID === 0x1915

**Comment by bencefr** [comment]
We decided to go ahead with the merge since we didn't find impact on the Programmer app.

**Pull request merged**
